// docs/prototype/src/app/pages/Login.tsx
import { useState } from "react";
import { useNavigate } from "react-router";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Button } from "../components/ui/button";
import { useAuth } from "../contexts/AuthContext";
import badgersLogo from "figma:asset/3ee6fb8dc3db20112c717dba8d1a4057e4616e05.png";
import { toast } from "sonner";
import { Lock, Mail } from "lucide-react";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      await login(email, password);
      toast.success("Welcome back!", {
        description: "Successfully logged in to Badgers Finance",
      });
      navigate("/");
    } catch (error) {
      toast.error("Login failed", {
        description: error instanceof Error ? error.message : "Please check your credentials and try again",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-emerald-50 flex items-center justify-center p-6">
      <div className="w-full max-w-md">
        {/* Logo and Branding */}
        <div className="text-center mb-8">
          <img src={badgersLogo} alt="Badgers Finance" className="h-20 mx-auto mb-4" />
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Badgers Finance</h1>
          <p className="text-gray-600">Investment Monitoring & Recommendations</p>
        </div>

        {/* Login Card */}
        <Card className="border-2 border-emerald-100 shadow-xl">
          <CardHeader className="space-y-1 pb-6">
            <CardTitle className="text-2xl text-center">Sign in to your account</CardTitle>
            <CardDescription className="text-center">
              Enter your credentials to access your portfolio
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <div className="relative">
                  <Mail className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                  <Input
                    id="email"
                    type="email"
                    placeholder="demo@badgers.finance"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                    className="pl-10"
                    autoComplete="email"
                  />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <div className="relative">
                  <Lock className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                  <Input
                    id="password"
                    type="password"
                    placeholder="Enter your password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    required
                    className="pl-10"
                    autoComplete="current-password"
                  />
                </div>
              </div>

              <Button
                type="submit"
                className="w-full bg-emerald-600 hover:bg-emerald-700 text-white"
                disabled={isLoading}
              >
                {isLoading ? "Signing in..." : "Sign in"}
              </Button>
            </form>

            {/* Demo Credentials Info */}
            <div className="mt-6 p-4 bg-emerald-50 border border-emerald-200 rounded-lg">
              <p className="text-sm font-medium text-emerald-900 mb-2">Demo Credentials:</p>
              <div className="text-sm text-emerald-800 space-y-1">
                <p><span className="font-medium">Email:</span> demo@badgers.finance</p>
                <p><span className="font-medium">Password:</span> badgers123</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Footer */}
        <p className="text-center text-sm text-gray-600 mt-6">
          &copy; 2026 Badgers Finance. All rights reserved.
        </p>
      </div>
    </div>
  );
}

// apps/web/src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { apiClient } from '$lib/api/api-client-instance';
  import { toast } from '$lib/toast/toast';
  import { Lock, User } from 'lucide-svelte';

  let username: string = '';
  let password: string = '';
  let isSubmitting: boolean = false;

  async function executeLogin(): Promise<void> {
    if (isSubmitting) {
      return;
    }
    isSubmitting = true;
    try {
      await apiClient.executeJson<
        { readonly user: { readonly userId: string; readonly username: string } },
        { readonly username: string; readonly password: string }
      >({
        method: 'POST',
        path: '/auth/login',
        body: { username: username.trim(), password },
      });
      toast.success('Welcome back!', {
        description: 'Successfully logged in to Badgers Finance',
      });
      await goto('/dashboard');
    } catch {
      toast.error('Login failed', {
        description: 'Unable to sign in. Check your credentials and try again.',
      });
    } finally {
      isSubmitting = false;
    }
  }
</script>

<svelte:head>
  <title>Login · Badgers Finance</title>
</svelte:head>

<!-- Matches docs/prototype/src/app/pages/Login.tsx layout (Tailwind + shadcn tokens) -->
<div
  class="flex min-h-screen items-center justify-center bg-gradient-to-br from-emerald-50 via-white to-emerald-50 p-6 dark:from-emerald-950/30 dark:via-background dark:to-emerald-950/30"
>
  <div class="w-full max-w-md">
    <div class="mb-8 text-center">
      <img src="/badgers-logo.png" alt="Badgers Finance" class="mx-auto mb-4 h-20 w-auto" />
      <h1 class="mb-2 text-3xl font-bold text-gray-900 dark:text-foreground">Badgers Finance</h1>
      <p class="text-gray-600 dark:text-muted-foreground">Investment Monitoring &amp; Recommendations</p>
    </div>

    <div
      class="rounded-xl border-2 border-emerald-100 bg-card text-card-foreground shadow-xl dark:border-emerald-900/40"
    >
      <div class="space-y-1 px-6 pb-6 pt-6">
        <h2 class="text-center text-2xl font-semibold">Sign in to your account</h2>
        <p class="text-center text-sm text-muted-foreground">
          Enter your credentials to access your portfolio
        </p>
      </div>
      <div class="px-6 pb-6">
        <form class="space-y-4" on:submit|preventDefault={executeLogin}>
          <div class="space-y-2">
            <label class="text-sm font-medium leading-none" for="login-username">Username</label>
            <div class="relative">
              <User class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />
              <input
                id="login-username"
                class="flex h-9 w-full rounded-md border border-input bg-input-background px-3 py-1 pl-10 text-base shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 md:text-sm dark:border-input"
                type="text"
                autocomplete="username"
                placeholder="your-username"
                bind:value={username}
                required
              />
            </div>
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium leading-none" for="login-password">Password</label>
            <div class="relative">
              <Lock class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />
              <input
                id="login-password"
                class="flex h-9 w-full rounded-md border border-input bg-input-background px-3 py-1 pl-10 text-base shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 md:text-sm dark:border-input"
                type="password"
                autocomplete="current-password"
                placeholder="Enter your password"
                bind:value={password}
                required
              />
            </div>
          </div>

          <button
            type="submit"
            class="inline-flex h-10 w-full items-center justify-center rounded-md bg-emerald-600 px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-emerald-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            disabled={isSubmitting}
          >
            {isSubmitting ? 'Signing in...' : 'Sign in'}
          </button>
        </form>

        <div class="mt-6 rounded-lg border border-emerald-200 bg-emerald-50 p-4 dark:border-emerald-800 dark:bg-emerald-950/40">
          <p class="mb-2 text-sm font-medium text-emerald-900 dark:text-emerald-100">Local credentials</p>
          <div class="space-y-1 text-sm text-emerald-800 dark:text-emerald-200/90">
            <p><span class="font-medium">Username:</span> your <code class="rounded bg-white/70 px-1 dark:bg-black/20">BOOTSTRAP_USERNAME</code></p>
            <p><span class="font-medium">Password:</span> your <code class="rounded bg-white/70 px-1 dark:bg-black/20">BOOTSTRAP_PASSWORD</code></p>
            <p class="mt-2 border-t border-emerald-200 pt-2 text-xs text-emerald-800 dark:border-emerald-800 dark:text-emerald-300/90">
              Run <code class="rounded bg-white/70 px-1 dark:bg-black/20">pnpm bootstrap:user</code> from the repo root (see README).
            </p>
          </div>
        </div>
      </div>
    </div>

    <p class="mt-6 text-center text-sm text-gray-600 dark:text-muted-foreground">
      &copy; 2026 Badgers Finance. All rights reserved.
    </p>
  </div>
</div>
